name: Render Markdown to HTML and PDF

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  render-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Pandoc and Tectonic
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Render Markdown to HTML
      run: pandoc -f markdown -t html5 -o index.html cvnn.md

    - name: Render Markdown to PDF
      run: pandoc --from=gfm --to=pdf -o cvnn.pdf cvnn.md

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push Changes
      run: |
        git add index.html cvnn.pdf
        git commit -m "Update index.html and cvnn.pdf from cvnn.md"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
