name: Render Markdown to HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  render-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Render Markdown to HTML
      run: pandoc -f markdown -t html5 -o index.html cvnn.md

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push Changes
      run: |
        git add index.html
        git commit -m "Update index.html from cvnn.md"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
